/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 DragonAttenuation.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DragonAttenuation.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_Backdrop.geometry} material={materials['Cloth Backdrop']} position={[-0.155, -0.842, -0.17]} scale={3.5} />
      <mesh geometry={nodes.Dragon.geometry} material={materials['Dragon with Attenuation']} position={[0, -0.731, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
    </group>
  )
}

useGLTF.preload('/DragonAttenuation.gltf')
